In [1]:
import torch
import torch.nn as nn

def view_weights_and_biases(rcv_model):
    """ This method prints out the weights and biases of a model """
    print('Viewing weights and biases')
    for name, param in rcv_model.named_parameters():
        if param.requires_grad:
            print(name, param.data)



# Defining the model
model = nn.Sequential(
    # This is the 1st input layer
        # THe data when passed into the Sequential, the number of elements must match what is defined in the 
        #  first layer. THe first layer expects an Array(List object) of 3 elements. The output from the 1st
        #  layer will be a 2 element Array. Whatever is taking place for the output is the hidden layer, that gets passed
        #  to the 2nd layer(nn.Linear(2,1)
    nn.Linear(3,2),
    # This is the 2nd layer, which receives the hidden layer(output from 1st layer, computations)
    #  which is a 2 element list object
    nn.Linear(2,1), 
    nn.Sigmoid()  # Activation Layer

)

view_weights_and_biases(model)


# The number of elements must match what is defined in the 1st layer of the model
input_data_list = [1., 1., 1.]
input_tensor = torch.tensor(input_data_list)  # Create a tensor object
print(input_tensor.dtype)
#print(dir(input_tensor))

output = model(input_tensor)

print(f'first set of data output for input of {input_data_list}')
print(output)
view_weights_and_biases(model)

input_data_list = [ 
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9],  # each sub-list within the tensor would receive a binary classification
    [1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5]
]

input_tensor = torch.tensor(input_data_list)  # Create a new tensor object(Really reusing but overriding)
output = model(input_tensor)

print(f'second set of data output for input of {input_data_list}')
print(output)

# Leaving this case here to force the model to fail, due to the tensor will be of type Int and not float
input_data_list = [1, 1, 1]
input_tensor = torch.tensor(input_data_list)  # Create a new tensor object(Really reusing but overriding)
print(input_tensor.dtype)
# If a tensor object created is of type INT and the input layer is Linear, RuntimeError will occur. Linear expects float values
try:    
    output = model(input_tensor)
except RuntimeError as err:
    print(f'RuntimeError = {err}')
    #print(type(err), dir(err))

    # If the 'err' object is not evaluated as an f-string it will not evalyate correceclty and ignore this
    if f'{err}' == 'mat1 and mat2 must have the same dtype, but got Long and Float':
        print(f'Converting tensor from datatype {input_tensor.dtype} to type float')
        # Convert integer tensor to a float tensor
        input_tensor = input_tensor.float()
        output = model(input_tensor)
    else:
        raise RuntimeError(f'{err}')

print(f'third set of data output for input of {input_data_list}')
print(output)






Viewing weights and biases
0.weight tensor([[-0.1010, -0.4949,  0.0177],
        [ 0.3016, -0.4133,  0.2075]])
0.bias tensor([-0.0256,  0.3853])
1.weight tensor([[ 0.5785, -0.5835]])
1.bias tensor([-0.6491])
torch.float32
first set of data output for input of [1.0, 1.0, 1.0]
tensor([0.2177], grad_fn=<SigmoidBackward0>)
Viewing weights and biases
0.weight tensor([[-0.1010, -0.4949,  0.0177],
        [ 0.3016, -0.4133,  0.2075]])
0.bias tensor([-0.0256,  0.3853])
1.weight tensor([[ 0.5785, -0.5835]])
1.bias tensor([-0.6491])
second set of data output for input of [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9], [1.0, 1.1, 1.2], [1.3, 1.4, 1.5]]
tensor([[0.2780],
        [0.2551],
        [0.2335],
        [0.2132],
        [0.1942]], grad_fn=<SigmoidBackward0>)
torch.int64
RuntimeError = mat1 and mat2 must have the same dtype, but got Long and Float
Converting tensor from datatype torch.int64 to type float
third set of data output for input of [1, 1, 1]
tensor([0.2177], grad_fn=<Sigmo